create schema if not exists sourcesys;

create table if not exists sourcesys.people (
    id bigint generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    email varchar(255) unique,
    birth_date date
);

create table if not exists sourcesys.departments (
    id bigint generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    department_name varchar(150) not null unique,
    description text
);

create table if not exists sourcesys.projects (
    id bigint generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    project_name varchar(150) not null,
    start_date date,
    status varchar(50) not null default 'active'
);